In [3]:
import pandas as pd
import numpy as np
from datetime import datetime
import requests
from pandas.io.json import json_normalize

In [2]:
price_df = pd.read_csv('SWE_PRICE_20YEAR.csv')
price_df['d'] = pd.to_datetime(price_df['d'])
price_df = price_df.set_index(['d', 'insID'])

In [4]:
# get splits

URL = "https://apiservice.borsdata.se/v1/Instruments/StockSplits?authKey=f4e8e3c7c46c4c34ae238a1822863410"
response = requests.get(URL)

In [7]:
tmp_df = json_normalize(response.json(), record_path ='stockSplitList')

In [8]:
tmp_df

    instrumentId splitType  ratio            splitDate
0            926         S   10:1  2020-12-23T00:00:00
1             48        RS   1:10  2020-12-28T00:00:00
2            797        RS   1:50  2020-12-21T00:00:00
3            548        RS  1:100  2021-01-08T00:00:00
4           1394        RS   1:20  2021-01-08T00:00:00
5            393         S    5:1  2021-01-18T00:00:00
6           1074        RS   1:10  2021-02-03T00:00:00
7            255         N  6,8:1  2021-02-19T00:00:00
8            917         S    3:1  2021-03-15T00:00:00
9           2005         S   10:1  2021-03-03T00:00:00
10           760        RS  1:100  2021-03-16T00:00:00
11           529        RS  1:400  2021-03-05T00:00:00
12           310        RS   1:10  2021-02-24T00:00:00
13            28         S    3:1  2021-04-23T00:00:00
14           752         S   10:1  2021-04-23T00:00:00
15           278         S   10:1  2021-04-27T00:00:00
16           940         S    5:1  2021-04-27T00:00:00
17           168         S    3:1  2021-05-03T00:00:00
18           218         S   10:1  2021-05-07T00:00:00
19           440         S    5:1  2021-05-06T00:00:00
20           348        RS   1:25  2021-05-06T00:00:00
21           158         S   10:1  2021-05-12T00:00:00
22            98         S    7:1  2021-05-19T00:00:00
23           181         S    3:1  2021-05-19T00:00:00
24           113         S    4:1  2021-05-19T00:00:00
25          1617         S    4:1  2021-05-19T00:00:00
26           480         S   10:1  2021-05-20T00:00:00
27           430        RS  1:100  2021-05-17T00:00:00
28           992        RS  1:100  2021-05-17T00:00:00
29          1312         S    5:1  2021-05-24T00:00:00
30          1011         S    5:1  2021-05-25T00:00:00
31           156         S    4:1  2021-05-25T00:00:00
32          1487         S    4:1  2021-05-26T00:00:00
33          1133         S   10:1  2021-05-31T00:00:00
34          1132         S   10:1  2021-06-03T00:00:00
35          1113        RS  1:100  2021-06-02T00:00:00
36          1887         S    6:1  2021-06-07T00:00:00
37           601         S    3:1  2021-06-07T00:00:00
38           769        RS   1:20  2021-06-07T00:00:00
39           908         S   10:1  2021-06-17T00:00:00
40           234        RS   1:10  2021-06-30T00:00:00
41           754         S    3:1  2021-06-30T00:00:00
42          2088         S   10:1  2021-06-30T00:00:00
43           970        RS  1:100  2021-07-13T00:00:00
44          1933         S    4:1  2021-07-22T00:00:00
45          1897         S   10:1  2021-08-05T00:00:00
46           385        RS   1:50  2021-08-24T00:00:00
47           619        RS   1:50  2021-08-24T00:00:00
48          1328        RS   1:50  2021-08-24T00:00:00
49           221         S    4:1  2021-09-06T00:00:00
50           200         S    5:1  2021-09-24T00:00:00
51          1374         S    2:1  2021-09-29T00:00:00
52          1401        RS   1:50  2021-09-20T00:00:00
53          2002         S   10:1  2021-09-30T00:00:00
54          1536        RS   1:10  2021-08-06T00:00:00
55          1853         F    5:1  2021-10-21T00:00:00
56           432        RS  1:100  2021-10-25T00:00:00
57           189        RS   1:50  2021-11-04T00:00:00
58           167        RS   1:10  2021-11-23T00:00:00
59           325        RS  1:100  2021-12-10T00:00:00